### ISSUE TITLE
DNS resolver (pen test related fix)

### ISSUE THREAD

**Issue by akolensky** [Barts-Life-Science/AzureTRE#126] opened 2024-08-02 09:34 UTC
## Issue
Arbitrary DNS queries were allowed outbound from the restricted environment. This could allow an attacker to perform DNS tunnelling in order to execute bidirectional data transfers, as well as access the Internet.

**Comment by TonyWildish-BH** [comment] 2024-08-16 08:35
this is a duplicate of https://github.com/Barts-Life-Science/AzureTRE/issues/125, which has more details from the upstream discussions.

**Closed by TonyWildish-BH** 2024-08-16 08:35 UTC
